### ISSUE TITLE
CRAN v2 roadmap

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#28]
# Features 

## Plan
- [x] generalise `p values`
- [x] generalise `ci`
- [ ] Check that it works for rstanarm and brms models
- [ ] Check that it works for frequentist models

## Optional (possibly for v2)
- [x] `se` for standards errors #29 
- [ ] Marginal coefs
- [ ] Conditional equivalence

# Other
- [ ] testing
- [ ] documentation

**Comment by strengejacke** [comment]
I think we need to push the dev of this package the next time a bit, though or because there is quite some work to do. But I would love to have this package available on CRAN by summer.

**Comment by DominiqueMakowski** [comment]
Yes I think the sooner the better. Right now, one of the blocker is to update `describe_posterior` and adjust parameters to its new version in bayestestR.

**Comment by DominiqueMakowski** [comment]
In my opinion, we could possibly go live (if everybody is happy with the API) anytime soon, with this limited amount of models that we support, and then focus on expanding the support. What do you think?

**Comment by strengejacke** [comment]
I'm on vacation from Friday and have some things to finish before, so I'm out of easystats the next 2 1/2 weeks.

I would say yes, parameters is ready for initial release.

**Comment by DominiqueMakowski** [comment]
v1 has been submitted

**Comment by strengejacke** [comment]
Any news on the state of submission for parameters?

**Comment by DominiqueMakowski** [comment]
Need the new bayestestR to go in as it requires `reshape_ci`

**Comment by strengejacke** [comment]
ok, thanks!

**Comment by DominiqueMakowski** [comment]
IMO we could (finally) submit parameters tomorrow, main issues have been fixed no?

**Comment by strengejacke** [comment]
yes.

**Comment by IndrajeetPatil** [comment]
Are there plans to resubmit this to CRAN any time soon?

I plan to add import it in my own package and I can wait if it is going to be submitted to CRAN soon.

**Comment by DominiqueMakowski** [comment]
yes, I'll submit tomorrow!

**Comment by DominiqueMakowski** [comment]
(i.e., in about 9 hours)

**Comment by DominiqueMakowski** [comment]
(submitted)

**Comment by strengejacke** [comment]
Yay: https://cran.r-project.org/web/packages/parameters/index.html 🎉

**Comment by DominiqueMakowski** [comment]
finally :)
